HOME = "/xxx/yyy"
POS_DB_PATH = HOME+"/fma_real_medium/resampled"
NEG_DB_PATH = HOME+"/fma_rebuilt_medium"
CODEC_DB_PATH = HOME+"/fma_codec/"
WEIGHTS_PATH = HOME+"/deepfake/weights/final"
RESULT_PATH = HOME+"/deepfake/results/final"
SPLIT_PATH = HOME+"/deepfake/data/dataset_medium_split.npy"
CONF_PATH = HOME+"/deepfake/conf"