HOME = "/xxx/yyy"
POS_DB_PATH = HOME+"/fma_real_medium/resampled"
NEG_DB_PATH = HOME+"/fma_rebuilt_medium"
CODEC_DB_PATH = HOME+"/fma_codec/"
WEIGHTS_PATH = HOME+"/weights/final"
RESULT_PATH = HOME+"/results/final"
SPLIT_PATH = HOME+"/data/dataset_medium_split.npy"
CONF_PATH = HOME+"/conf"